### ISSUE TITLE
Refactor and add tests

### ISSUE THREAD

**Issue by maxachis** [Police-Data-Accessibility-Project/data-sources-mirror#59]
To ensure the mirroring functionality operates properly, and to make it easier to modify changes without worrying about something breaking, we should add integration tests.

Compared with the tests in https://github.com/Police-Data-Accessibility-Project/data-sources-app-v2, these would be limited to integration tests, since there isn't a lot of middleware and we would eventually be replacing this logic with calls to endpoints. The tests would need to be performed on a stage or sandbox version of the database. 

Additionally, code within the repository would need to be refactored to be more easily testable.

**Comment by maxachis** [comment]
# Implementation Todo

- [ ] Create intermediate data objects that contain all the possible fields for each of the airtable tables. 
- [ ] Create constants for the database table names (as opposed to the functions which currently exist). Place in `constants.py` file.
- [ ] Modify `full_mirror_to_digital_ocean` so that logic past `get_full_table_data` does not occur if there are no new rows.
- [ ] Break up logic into separate files for airtable-side, database-side, and middleware.
- [ ] Build integration tests that add data to database and confirm that expected keys are present.

**Comment by maxachis** [comment]
# Tests

## TODO
### Create tests for 
- [ ] Agencies
- [ ] Data Sources (and link to Agencies)
- [ ] Counties
- [ ] Data Requests

## Test Implementation Notes
* In each test case, mock `get_recent_airtable_data()` (a new function I've created in this branch) to return _exactly_ all the values you would get in a full form submission from airtable.
* Similarly, mock `update_do_table()` to test that it gets _exactly_ the results it is currently receiving when you run it for that test case.

These two points will be necessary in order to ensure that modifications of the code do not break anything when the middleware is being changed.
